(defun draw-main-menu-castle ()
  (center-caption "C A S T L E")
  (goto-xy 0 4)
  (draw-string "#")
  (goto-xy 79 4)
  (draw-string "#")
  (goto-xy 0 4)
  (draw-string (align-center "A)dventure's Inn" 0))
  (goto-xy 0 5)
  (draw-string (align-center "G)ilgamesh's Travarn" 0))
  (goto-xy 0 6)
  (draw-string (align-center "B)oltac's Trading Post" 0))
  (goto-xy 0 7)
  (draw-string (align-center "Temple of C)ant" 0))
  (goto-xy 0 8)
  (draw-string (align-center "E)dge of Town" 0))
  (goto-xy 0 21)
  (draw-string (align-center "[ESC] Back to Main Title" 0))
  (sdl:update-display))

(defun keydown-castle (k)
  (when (sdl:key= k :sdl-key-escape)
    (progn
      (setf *game-mode* :main-title)
      (sdl:push-quit-event))))
  
(defun castle-main ()
  (fill-screen sdl:*white*)
  (draw-main-menu-castle)
  (sdl:with-events ()
    (:quit-event () t)
    (:key-down-event (:key key)
		     (keydown-castle key))
    (:idle
     (sdl:update-display))))
